spring.application.name=Project_Monday

spring.datasource.url=jdbc:mysql://localhost:3306/project_monday
spring.datasource.username=root
spring.datasource.password=dhana
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
#recreation avoiding

spring.jpa.show-sql=true
#show SQL queries while program running